### PR TITLE
feat: w-full widgets

### PR DESCRIPTION
**Pull request by depressedPlumber502**

### CODE REVIEW

**Comment by depressedPlumber502** [comment]
> Please add some reasonable max size.
And what if eventually someone wants to have a bigger size than the one set by me? What do they do? Open a PR for passing className string to override the value ?

**Comment by cawabunga-bytes** [comment]
I doubt consumers will want to have 1000px widget, what do you think?

**Comment by depressedPlumber502** [comment]
Set default width to 472px as before

**Pull request merged**
